[package]
name = "ez_logger"
version = "0.1.0"
authors = ["Oleg Sheynin <oleg1@sheynin.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = ">=0.4.11"
strfmt = "0.1.6"
lazy_static = "1.4.0"
